# Generated by Django 5.2.8 on 2026-10-01 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.CharField(blank=True, max_length=240)),
                ("icon", models.CharField(default="🌱", max_length=8)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "price",
                    models.PositiveIntegerField(help_text="Price in Kenyan shillings"),
                ),
                ("old_price", models.PositiveIntegerField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="products/")),
                ("badge", models.CharField(blank=True, max_length=30)),
                ("featured", models.BooleanField(default=False)),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("InStock", "In stock"),
                            ("PreOrder", "Available to order"),
                            ("OutOfStock", "Out of stock"),
                        ],
                        default="InStock",
                        max_length=24,
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-featured", "name"],
            },
        ),
    ]
