# Generated by Django 5.2.17 on 2026-10-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_is_active_promotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique key identifier for template lookup",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human readable field title", max_length=120
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        default="General",
                        help_text="Category group for editor organization",
                        max_length=60,
                    ),
                ),
                ("value", models.TextField(blank=True, default="")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Single-line Text"),
                            ("textarea", "Multi-line Text"),
                            ("html", "Rich HTML / Markdown"),
                            ("boolean", "Boolean Switch (true/false)"),
                            ("url", "URL Link"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("help_text", models.CharField(blank=True, default="", max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
                "ordering": ["group", "label"],
            },
        ),
    ]
